### DISCUSSION TITLE
Color Scheme — Glitch Ui

### DISCUSSION THREAD

**Discussion by Exios66** [Exios66/morningstar-portfolio#6] [Ideas]
## Color Scheme:

The CSS code uses a series of CSS variables (--color-bg-1, --color-bg-2, --color-text, --color-accent) for consistent styling throughout the page. Here are the extracted colors:

CSS Variable	Description	Color Value
--color-bg-1	Background Gradient Color 1	#120458 (Deep Indigo)
--color-bg-2	Background Gradient Color 2	#000000 (Black)
--color-text	Text and Particle Color	#00fff1 (Cyan/Aqua)
--color-accent	Accent Color	#ff00ff (Magenta)

Extracted CSS:

```css
:root {
    --color-bg-1: #120458;
    --color-bg-2: #000000;
    --color-text: #00fff1;
    --color-accent: #ff00ff;
}

body, html {
    margin: 0;
    padding: 0;
    font-family: 'Orbitron', sans-serif;
    height: 100%;
    overflow: hidden;
    background: linear-gradient(45deg, var(--color-bg-1), var(--color-bg-2));
}

```
```css
.error-page {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 100vh;
    position: relative;
    z-index: 1;
}

```
```css
.glitch {
    font-size: 15vw;
    font-weight: bold;
    color: var(--color-accent);
    text-shadow: 
        0.05em 0 0 var(--color-text),
        -0.025em -0.05em 0 var(--color-bg-1),
        0.025em 0.05em 0 var(--color-bg-2);
    animation: glitch 500ms infinite;
}

@keyframes glitch {
    0%, 14% {
        text-shadow: 
            0.05em 0 0 var(--color-text),
            -0.05em -0.025em 0 var(--color-bg-1),
            -0.025em 0.05em 0 var(--color-bg-2);
    }
    15%, 49% {
        text-shadow: 
            -0.05em -0.025em 0 var(--color-text),
            0.025em 0.025em 0 var(--color-bg-1),
            -0.05em -0.05em 0 var(--color-bg-2);
    }
    50%, 99% {
        text-shadow: 
            0.025em 0.05em 0 var(--color-text),
            0.05em 0 0 var(--color-bg-1),
            0 -0.05em 0 var(--color-bg-2);
    }
    100% {
        text-shadow: 
            -0.025em 0 0 var(--color-text),
            -0.025em -0.025em 0 var(--color-bg-1),
            -0.025em -0.05em 0 var(--color-bg-2);
    }
}
```

```css
.btn {
    display: inline-block;
    padding: 15px 30px;
    background-color: var(--color-accent);
    color: var(--color-bg-1);
    text-decoration: none;
    border-radius: 5px;
    font-size: 1.1rem;
    font-weight: bold;
    text-transform: uppercase;
    transition: all 0.3s ease;
    margin-top: 20px;
    border: 2px solid var(--color-text);
}

```
```css
.btn:hover {
    background-color: var(--color-text);
    color: var(--color-accent);
    box-shadow: 0 0 15px var(--color-text);
}
```

```css
.particles {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
    z-index: -1;
}

```
```css
.particle {
    position: absolute;
    background-color: var(--color-text);
    border-radius: 50%;
    opacity: 0.5;
}
```

Summary of Style Elements:

	1.	Root Colors: Defined via :root for easy maintenance:
	•	Background colors form a gradient from #120458 to #000000.
	•	Text colors are primarily cyan/aqua (#00fff1).
	•	Accent colors are magenta (#ff00ff).
	2.	Body and HTML Styles:
	•	Utilizes a gradient background with a linear transition (45deg).
	•	Full-screen layout with 100% height and overflow hidden.
	3.	Error Page Styling:
	•	Flexbox alignment (.error-page) to center content vertically and horizontally.
	•	A glitchy animated “404” (.glitch) is styled with text-shadow and animation (glitch keyframe).
	4.	Button (.btn):
	•	Magenta background (--color-accent) with rounded corners.
	•	Changes to cyan/aqua (--color-text) on hover, with a box shadow for emphasis.
	5.	Particles:
	•	Particles are styled as small circles (.particle) with a background color of cyan (--color-text) and semi-transparency.
